<iframe src="https://github.com/sponsors/geraldopatricio/button" title="Sponsor geraldopatricio" height="32" width="114" style="border: 0; border-radius: 6px;"></iframe>

github: [octocat, surftocat]
patreon: octocat
tidelift: npm/octo-package
custom: ["https://www.paypal.me/octocat", octocat.com]

